---
- name: "Download filebaet's deb"
  get_url:
    url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-{{ filebeat_version }}-amd64.deb"
    dest: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    mode: 0755
    validate_certs: false
  register: download_filebeat
  until: download_filebeat is succeeded
      
   