---
- name: "Download filebaet's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-x86_64.deb"
    dest: "/tmp/filebeat-{{ filebeat_version }}-x86_64.deb"
    validate_certs: false
  register: download_filebeat
  until: download_filebeat is succeeded
      
   