---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Check that the filebeat.yml exists
    stat:
      path: /etc/filebeat/filebeat.yml
    register: stat_result
    failed_when: not stat_result.stat.exists
  - name: get fact
    service_facts:
  - name: Check if filebeat is running 
    assert:
      that:
        ansible_facts.services["filebeat.service"].state == "running"
      fail_msg: "Filebeat service not running"
      success_msg: "Filebeat service running"
